Expose `buf_index`
tokio-rs/tokio-uring pull request #187
Opened 2022-11-26 19:07 UTC by Nehliin

This makes it easier to build abstractions on top of the `FixedBufferRegistry`. Use case I have is having a wrapping struct which keeps track of occupied buffers using a bitset. It can also create thread safe handles to these buffers from the `FixedBuf` handles and it would be useful to know which index they were created from so the bitset can be updated in the destructor. I can work around it but it's a bit unnecessary to track the same information in multiple places and I don't see a reason from hiding this information from the users in the first place.

2022-11-30 21:58 UTC, mzabaluev approved these changes
I don't see a reason why buffer index should not be public.

In a future change to resolve #185 and enable other alternative fixed buffer collections, this method will be provided by a trait, which should be made public to enable off-crate implementations.

2022-11-30 22:14 UTC, FrankReh approved these changes
In for a penny, in for a pound.

2022-11-30 22:17 UTC, FrankReh commented
Looks like fmt is not happy. Maybe a space or tab left on that blank line above the doc comment?

2022-11-30 22:18 UTC, FrankReh requested changes
Seems time to make cargo fmt happy.

2022-12-01 12:28 UTC, FrankReh approved these changes

2022-12-01 12:30 UTC, merged