Add create_dir
tokio-rs/tokio-uring pull request #193
Opened 2022-12-02 05:43 UTC by kaimast

This adds a `create_dir` function call to `tokio_uring::fs` and partially fixes #48.

2022-12-02 11:08 UTC, FrankReh requested changes
Nice. Just minor stuff.

2022-12-02 11:08 UTC, FrankReh commented on src/io/mkdir_at.rs
> +        Ok(())
Also, like unlink_at.rs,
```rust
cqe.result.map(|_| ())
```

2022-12-03 22:56 UTC, FrankReh commented
@kaimast Would it be alright with you if I made the two tweaks and then merged?

2022-12-03 23:43 UTC, kaimast commented
Yes, of course.

2022-12-17 02:56 UTC, kaimast commented
I made the changes and also resolved conflicts with more recent changes in master.

2022-12-17 04:33 UTC, FrankReh approved these changes
Looks good. Thanks for getting to this.

2022-12-17 04:34 UTC, merged