Add method `BoundedBuf::put_slice`
tokio-rs/tokio-uring pull request #198
Opened 2022-12-04 22:17 UTC by mzabaluev

Provide a generic,  safe way to copy data into a buffer, possibly advancing the initialized length watermark.
This method is especially useful for `FixedBuf`, which lacks other population methods available for foreign types.

This resolves a discussion started in https://github.com/tokio-rs/tokio-uring/pull/190#issuecomment-1336301837

2022-12-04 23:57 UTC, FrankReh requested changes
Super.

~~Could you see the use cases for providing two other methods, one for zeroing to the init point and one for zeroing to the capacity and setting the init point to the capacity?~~

Seems code like
```rust
ary.iter_mut().for_each(|m| *m = 0)
```
~~is expected to be optimized to a memset call, per https://users.rust-lang.org/t/fastest-way-to-zero-an-array/39222
but that's from a few years ago.~~

One typo, and maybe wait for Noah's second commit today and this is good to go.

2022-12-04 23:57 UTC, FrankReh commented on src/buf/bounded.rs
> +    /// Copies the given byte slice slice into the buffer, starting at
'slice slice' -> 'slice'

2022-12-05 00:07 UTC, FrankReh commented
Following the discussion further, I see there is a slice fill method since 1.50.
https://doc.rust-lang.org/std/primitive.slice.html#method.fill

2022-12-05 00:39 UTC, Noah-Kennedy commented
Once the typo is fixed I'm in favor of merging.

2022-12-05 03:33 UTC, mzabaluev commented on src/buf/bounded.rs
> +    /// Copies the given byte slice slice into the buffer, starting at
https://github.com/tokio-rs/tokio-uring/pull/198/commits/83519e4fc1cd8d58a78487c58fa74fe8e096ca08

2022-12-05 03:58 UTC, FrankReh approved these changes
Thanks

2022-12-05 03:58 UTC, merged