fs: implement `rename`
tokio-rs/tokio-uring pull request #96
Opened 2022-07-29 07:11 UTC by arashsm79

Implement the `rename` operation for `fs`.
This operation uses [`IORING_OP_RENAMEAT`](https://man.archlinux.org/man/io_uring_enter.2.en#IORING_OP_RENAMEAT) as the opcode for the submitted
SQE.

Both file descriptors are set to the special value `AT_FDCWD` so that
the given paths are interpreted relative to the current working
directory of the calling process. [[1]](#1)

The operation is submitted with a zero `flags` argument so that it would
be equivalent to the corresponding operation in [`tokio:fs`](https://docs.rs/tokio/latest/tokio/fs/fn.rename.html)/[`std:fs`](https://doc.rust-lang.org/std/fs/fn.rename.html). [[1]](#1)

Refs: #48

<a id="1">[1]</a> [`renameat2` syscall man page](https://man7.org/linux/man-pages/man2/renameat2.2.html)

2022-07-31 19:59 UTC, Noah-Kennedy requested changes
One minor thing, but this is great!

2022-07-31 19:59 UTC, Noah-Kennedy commented on src/driver/rename_at.rs
> +/// The given paths are interpreted relative to the current working directory
Add a newline between the first and second line.

2022-08-01 06:04 UTC, arashsm79 commented
Done.

2022-08-01 14:58 UTC, Noah-Kennedy approved these changes

2022-08-01 15:00 UTC, merged